// var left_btn =  id("left_btn").findOne()
// left_btn.click()
// var quzhuanqian = text("去赚钱").findOne()
var quzhuanqian = id("text1").findOne()
quzhuanqian.click()
// var x = left_btn.bounds().centerX()
// var y = left_btn.bounds().centerY()
// log(x)
// log(y)
// click(x, y)